title: <p align="center"> Debasish Deaty </p>
logo: /assets/img/logo.png

description: 
<p align="center">
<a href="https://www.linkedin.com/in/debasish-deaty-74545b48/">LinkedIn</a> |
<a href="https://github.com/ddeaty">GitHub</a>

 <br>   
I'm working on  network and Data Center architectural solutions.
Leading the Data Network Team in Wipro Ltd. for Data Center solutions.
With 14 years of experience.
<br>
</p>

theme: jekyll-theme-minimal
